services:
  sphinx:
    build:
      context: .
      dockerfile: docs/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/work
    environment:
      PYTHONPATH: "/work/src:/work"
    working_dir: /work
    command: sphinx-autobuild -M html /work/docs /work/docs/_build/html --host 0.0.0.0 --port 8000
