name: deploy reusable workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
      deploy-prod:
        required: false
        type: string
        default: "false"

jobs:
  pypi-test:
    if: ${{ inputs.deploy-prod == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment:
      name: test
      url: ${{ vars.PYPI_PROJECT_URL }}
    permissions:
      id-token: write   # needed for publishing to PyPI
      contents: read
    steps:
      - name: Download built distribution
        uses: actions/download-artifact@v5
        with:
          name: pypi-artifact
          path: dist/

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          repository-url: ${{ vars.PYPI_REPOSITORY_URL }}
          verbose: true
          # per issue, https://github.com/pypa/gh-action-pypi-publish/issues/166, reusable
          # workflows are not supported for trusted publishing
          password: ${{ secrets.PYPI_PASSWORD }}
          attestations: "false"

  pypi-prod:
    if: ${{ inputs.deploy-prod == 'true' }}
    needs: pypi-test
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{ vars.PYPI_PROJECT_URL }}
    permissions:
      id-token: write   # needed for publishing to PyPI
    steps:
      - name: Download built distribution
        uses: actions/download-artifact@v5
        with:
          name: pypi-artifact
          path: dist/

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          # per issue, https://github.com/pypa/gh-action-pypi-publish/issues/166, reusable
          # workflows are not supported for trusted publishing
          password: ${{ secrets.PYPI_PASSWORD }}
          attestations: "false"

  doc:
    if: ${{ inputs.deploy-prod == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
