name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: 'ubuntu-latest' 
    steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"

        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.release.target_commitish }}
            persist-credentials: false

        - uses: actions/setup-python@v5
          with:
            python-version: '3.13'
            cache: 'pip'
  
        - name: install deps
          run: pip install -r requirements-build.txt
  
        - name: build
          run: python3 -m build

        - name: Store the distribution packages
          uses: actions/upload-artifact@v4
          with:
            name: python-package-distributions
            path: dist/

  publish-pypi:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cycl
    permissions:
      id-token: write  # required for trusted publishing    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
