name: Release

on:  
  workflow_call:
    inputs:
      pre-release:
        required: true
        type: string
      python-version:
        required: false
        type: string
    secrets:
      token:
        required: true
    outputs:
      tag:
        description: "The value of the newly created tag."
        value: ${{ jobs.create.outputs.tag }}

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'  # fetches tags

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297  # v1.71.0
        env:
          DEFAULT_BUMP: patch
          GIT_API_TAGGING: false
          GITHUB_TOKEN: ${{ secrets.token }}
          PRERELEASE_SUFFIX: b
          PRERELEASE: ${{ inputs.pre-release }}
          WITH_V: false

      - name: Create release from tag
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          tag: ${{ steps.tag.outputs.new_tag }}
        run: |
          gh release create "${tag}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes
